### ISSUE TITLE
error when trying to edit a section of a node

### ISSUE THREAD

**Issue by algisinfo** [ymcatwincities/openy_gated_content#49]
```
[21-Oct-2020 09:38:13 America/New_York] PHP Warning:  Illegal string offset '_original_delta' in /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Field/WidgetBase.php on line 381
[21-Oct-2020 09:38:13 America/New_York] Error: Cannot unset string offsets in
/home/openy2up/openymca/docroot/modules/contrib/openy_gated_content/src/Plugin/Field/FieldWidget/
GatedContentPermissionsFieldWidget.php on line 119
#0 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Field/
WidgetBase.php
(390): Drupal\openy_gated_content\Plugin\Field\FieldWidget\GatedContentPermissionsFieldWidget->massageFormValues(Array, Array, Object(Drupal\Core\Form\FormState))
#1 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(232): Drupal\Core\Field\WidgetBase->extractFormValues(Object(Drupal\Core\Field\FieldItemList), Array, Object(Drupal\Core\Form\FormState))
#2 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(338): Drupal\Core\Entity\Entity\EntityFormDisplay->extractFormValues(Object(Drupal\node\Entity\Node), Array, Object(Drupal\Core\Form\FormState))
#3 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Entity/EntityForm.php(336): Drupal\Core\Entity\ContentEntityForm->copyFormValuesToEntity(Object(Drupal\node\Entity\Node), Array, Object(Drupal\Core\Form\FormState))
#4 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(159): Drupal\Core\Entity\EntityForm->buildEntity(Array, Object(Drupal\Core\Form\FormState))
#5 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(190): Drupal\Core\Entity\ContentEntityForm->buildEntity(Array, Object(Drupal\Core\Form\FormState))
#6 [internal function]: Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState))
#7 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array)
#8 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Form/FormValidator.php(273): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState))
#9 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'node_landing_pa...')
#10 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(589): Drupal\Core\Form\FormValidator->validateForm('node_landing_pa...', Array, Object(Drupal\Core\Form\FormState))
#11 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm('node_landing_pa...', Array, Object(Drupal\Core\Form\FormState))
#12 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Controller/FormController.php(91): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\node\NodeForm), Object(Drupal\Core\Form\FormState))
#13 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#14 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#15 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#16 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#17 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#18 /home/openy2up/openymca/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#19 /home/openy2up/openymca/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#20 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /home/openy2up/openymca/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /home/openy2up/openymca/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /home/openy2up/openymca/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /home/openy2up/openymca/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /home/openy2up/openymca/docroot/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /home/openy2up/openymca/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#30 {main}
```

**Comment by hamrant** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/145
